### PR TITLE
Add GitHub Actions to run tests on different versions of Python

### PR DESCRIPTION
**Pull request by traversaro**
This could help in catching possible regression, also in the environment (i.e. update in dependencies) as it runs a weekly job every monday. I used as a template from https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python and I modified it as needed.

As I was at it, I also remove the Travis file that was not used anymore.

### CODE REVIEW

**Review by fishbotics — APPROVED** [review]
LGTM. We can add more platforms in the future if necessary.

**Comment by traversaro** [comment]
@fishbotics if you think it is useful, I can also open a PR with the other action that I added in my fork of urdfpy: https://github.com/ami-iit/murdfpy/blob/master/.github/workflows/publish-to-test-pypi.yml . This job pushes a releases to PyPI whenever a new tag is done in the GitHub repo.

**Comment by fishbotics** [comment]
Yeah I think that would be great. I haven't used these Github actions before. How do you securely store the API KEY for Pypi?

**Comment by traversaro** [comment]
> Yeah I think that would be great. I haven't used these Github actions before. How do you securely store the API KEY for Pypi?

You add it as a [Repository Secret](https://docs.github.com/en/actions/security-guides/encrypted-secrets) in GitHub Action settings, see https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/ . See https://github.com/fishbotics/urchin/pull/5 for more details.

**Pull request merged**
